#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("br.com.weblayer.logistica.android.Resource", IsApplication=true)]

namespace br.com.weblayer.logistica.android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BordaBotoes = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int EditTextStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int PerformanceAmarelo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int PerformanceVerde = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int PerformanceVermelho = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int NotaListView = 2131034115;
			
			// aapt resource value: 0x7f05001b
			public const int PerformanceListView = 2131034139;
			
			// aapt resource value: 0x7f05000c
			public const int btnConfirmarEntrega = 2131034124;
			
			// aapt resource value: 0x7f050015
			public const int btnEntrar = 2131034133;
			
			// aapt resource value: 0x7f050026
			public const int btnEnviar = 2131034150;
			
			// aapt resource value: 0x7f050018
			public const int btnMenuInformaEntrega = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int btnMenuPerformanceEntrega = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int btnMenuSimularFrete = 2131034138;
			
			// aapt resource value: 0x7f050002
			public const int btnPesquisar = 2131034114;
			
			// aapt resource value: 0x7f050014
			public const int edtSenha = 2131034132;
			
			// aapt resource value: 0x7f050010
			public const int edtServidor = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int edtUsuario = 2131034130;
			
			// aapt resource value: 0x7f05000a
			public const int lblDataEntrega = 2131034122;
			
			// aapt resource value: 0x7f05001e
			public const int lblDestino = 2131034142;
			
			// aapt resource value: 0x7f05000d
			public const int lblMensagem = 2131034125;
			
			// aapt resource value: 0x7f050017
			public const int lblMenuUsuario = 2131034135;
			
			// aapt resource value: 0x7f050004
			public const int lblNome = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int lblNota = 2131034120;
			
			// aapt resource value: 0x7f05001c
			public const int lblOrigem = 2131034140;
			
			// aapt resource value: 0x7f050022
			public const int lblPesoNF = 2131034146;
			
			// aapt resource value: 0x7f050006
			public const int lblValor = 2131034118;
			
			// aapt resource value: 0x7f050020
			public const int lblValorNF = 2131034144;
			
			// aapt resource value: 0x7f050024
			public const int lblVolume = 2131034148;
			
			// aapt resource value: 0x7f05000e
			public const int linearLayout1 = 2131034126;
			
			// aapt resource value: 0x7f05002b
			public const int tbl1 = 2131034155;
			
			// aapt resource value: 0x7f050029
			public const int txtCliente = 2131034153;
			
			// aapt resource value: 0x7f05000b
			public const int txtDataEntrega = 2131034123;
			
			// aapt resource value: 0x7f05001f
			public const int txtDestino = 2131034143;
			
			// aapt resource value: 0x7f050016
			public const int txtMensagem = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int txtNomeCliente = 2131034117;
			
			// aapt resource value: 0x7f05002d
			public const int txtNomeTransportadora = 2131034157;
			
			// aapt resource value: 0x7f050009
			public const int txtNota = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int txtNumNota = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int txtNumerodaNota = 2131034112;
			
			// aapt resource value: 0x7f05001d
			public const int txtOrigem = 2131034141;
			
			// aapt resource value: 0x7f05002c
			public const int txtPerformance = 2131034156;
			
			// aapt resource value: 0x7f050023
			public const int txtPesoNF = 2131034147;
			
			// aapt resource value: 0x7f050027
			public const int txtRelativeLayout1 = 2131034151;
			
			// aapt resource value: 0x7f050013
			public const int txtSenha = 2131034131;
			
			// aapt resource value: 0x7f05002a
			public const int txtSerie = 2131034154;
			
			// aapt resource value: 0x7f05000f
			public const int txtServidor = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int txtUsuario = 2131034129;
			
			// aapt resource value: 0x7f050028
			public const int txtValor = 2131034152;
			
			// aapt resource value: 0x7f050021
			public const int txtValorNF = 2131034145;
			
			// aapt resource value: 0x7f050007
			public const int txtValorNota = 2131034119;
			
			// aapt resource value: 0x7f050025
			public const int txtVolume = 2131034149;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_BuscaNotaView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Activity_InformaEntrega = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Activity_Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Activity_Menu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Activity_Performance = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Activity_SimularFrete = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Adapter_NotaFiscal_ListView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Adapter_Performance_ListView = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
