#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("br.com.weblayer.logistica.android.Resource", IsApplication=true)]

namespace br.com.weblayer.logistica.android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BackButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BordaBotoes = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dialog_BuscaCidadeStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int EditTextStyle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int PerformanceAmarelo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int PerformanceVerde = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int PerformanceVermelho = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060039
			public const int CidadeListView = 2131099705;
			
			// aapt resource value: 0x7f060003
			public const int NotaListView = 2131099651;
			
			// aapt resource value: 0x7f06001b
			public const int PerformanceListView = 2131099675;
			
			// aapt resource value: 0x7f06000c
			public const int btnConfirmarEntrega = 2131099660;
			
			// aapt resource value: 0x7f060015
			public const int btnEntrar = 2131099669;
			
			// aapt resource value: 0x7f060027
			public const int btnEnviar = 2131099687;
			
			// aapt resource value: 0x7f060018
			public const int btnMenuInformaEntrega = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int btnMenuPerformanceEntrega = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int btnMenuSimularFrete = 2131099674;
			
			// aapt resource value: 0x7f060002
			public const int btnPesquisar = 2131099650;
			
			// aapt resource value: 0x7f060038
			public const int btnPesquisarCidade = 2131099704;
			
			// aapt resource value: 0x7f060014
			public const int edtSenha = 2131099668;
			
			// aapt resource value: 0x7f060010
			public const int edtServidor = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int edtUsuario = 2131099666;
			
			// aapt resource value: 0x7f06003a
			public const int iconVoltar = 2131099706;
			
			// aapt resource value: 0x7f06000a
			public const int lblDataEntrega = 2131099658;
			
			// aapt resource value: 0x7f06001f
			public const int lblDestino = 2131099679;
			
			// aapt resource value: 0x7f060036
			public const int lblInformarCidade = 2131099702;
			
			// aapt resource value: 0x7f06000d
			public const int lblMensagem = 2131099661;
			
			// aapt resource value: 0x7f060017
			public const int lblMenuUsuario = 2131099671;
			
			// aapt resource value: 0x7f060004
			public const int lblNome = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int lblNota = 2131099656;
			
			// aapt resource value: 0x7f06001d
			public const int lblOrigem = 2131099677;
			
			// aapt resource value: 0x7f060023
			public const int lblPesoNF = 2131099683;
			
			// aapt resource value: 0x7f060006
			public const int lblValor = 2131099654;
			
			// aapt resource value: 0x7f060021
			public const int lblValorNF = 2131099681;
			
			// aapt resource value: 0x7f060025
			public const int lblVolume = 2131099685;
			
			// aapt resource value: 0x7f06000e
			public const int linearLayout1 = 2131099662;
			
			// aapt resource value: 0x7f06001c
			public const int lstResultadoSimulacaoFrete = 2131099676;
			
			// aapt resource value: 0x7f06002b
			public const int tbl1 = 2131099691;
			
			// aapt resource value: 0x7f060028
			public const int txt1 = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int txt2 = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int txt3 = 2131099690;
			
			// aapt resource value: 0x7f06002c
			public const int txtCidade = 2131099692;
			
			// aapt resource value: 0x7f060030
			public const int txtCliente = 2131099696;
			
			// aapt resource value: 0x7f06000b
			public const int txtDataEntrega = 2131099659;
			
			// aapt resource value: 0x7f060020
			public const int txtDestino = 2131099680;
			
			// aapt resource value: 0x7f06002d
			public const int txtEstado = 2131099693;
			
			// aapt resource value: 0x7f060034
			public const int txtFrete = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int txtFreteImposto = 2131099701;
			
			// aapt resource value: 0x7f060037
			public const int txtInformarCidade = 2131099703;
			
			// aapt resource value: 0x7f060016
			public const int txtMensagem = 2131099670;
			
			// aapt resource value: 0x7f060005
			public const int txtNomeCliente = 2131099653;
			
			// aapt resource value: 0x7f060033
			public const int txtNomeTransportadora = 2131099699;
			
			// aapt resource value: 0x7f060009
			public const int txtNota = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int txtNumNota = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int txtNumerodaNota = 2131099648;
			
			// aapt resource value: 0x7f06001e
			public const int txtOrigem = 2131099678;
			
			// aapt resource value: 0x7f060032
			public const int txtPerformance = 2131099698;
			
			// aapt resource value: 0x7f060024
			public const int txtPesoNF = 2131099684;
			
			// aapt resource value: 0x7f06002e
			public const int txtRelativeLayout1 = 2131099694;
			
			// aapt resource value: 0x7f060013
			public const int txtSenha = 2131099667;
			
			// aapt resource value: 0x7f060031
			public const int txtSerie = 2131099697;
			
			// aapt resource value: 0x7f06000f
			public const int txtServidor = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int txtUsuario = 2131099665;
			
			// aapt resource value: 0x7f06002f
			public const int txtValor = 2131099695;
			
			// aapt resource value: 0x7f060022
			public const int txtValorNF = 2131099682;
			
			// aapt resource value: 0x7f060007
			public const int txtValorNota = 2131099655;
			
			// aapt resource value: 0x7f060026
			public const int txtVolume = 2131099686;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_BuscaNotaView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Activity_InformaEntrega = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Activity_Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Activity_Menu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Activity_Performance = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Activity_SimulacaoFreteResultado = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Activity_SimularFrete = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Activity_TabelaResultadoFrete = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Adapter_Cidade_ListView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Adapter_NotaFiscal_ListView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Adapter_Performance_ListView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Adapter_SimulacaoFrete_ListView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Fragment_BuscarCidade = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int XMLFile1 = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
